version: "3.7"

services:
  jenkins:
    image: thanhminh.hodac/jenkins
    build:
      context: .
      dockerfile: jenkins.Dockerfile
      tags:
        - "thanhminh.hodac/jenkins:2.401.3-lts-jdk11"
    container_name: jenkins-dev
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - "jenkins-data:/var/jenkins_home"
      - "jenkins-docker-certs:/certs/client:ro"
    restart: on-failure
    networks:
      - jenkins

networks:
  jenkins:
    external: true

volumes:
  jenkins-data:
  jenkins-docker-certs:
